### ISSUE TITLE
Refactor the code: Separate the interactions from the objects

### ISSUE THREAD

**Issue by eetumans** [evktalo/kiigame#17]
Currently the interactions are done via the objects from the JSON and are very limited.
Current implementation does not for example support multiple interactions for the same items/objects.

The interactions could be separated into their own JSON and the code would have to be refactored to support this.

**Comment by evktalo** [comment]
Here's a list of things that can happen in an interaction:
* Destroy an object from the room
* Add an object to the room
* Destroy an item from the inventory (inc. currently dragged item)
* Add an item to the inventory
* Start a monologue (i.e. output some text)
* Transition to another room
* Play a sequence (a cutscene)
* End the game

Many of these can happen in the same interaction.

There would be no special case objects, such as doors or containers. Such functionality would be defined in the interactions. (An editor for making adventures could contain such special cases as templates for easier adventure creation).

**Comment by evktalo** [comment]
Everything else seems quite straightforward, but I'd like adding items to inventory without them existing in the stage beforehand. They should exist as room objects (or "furniture") before being picked up, and created to the inventory, instead of being moved there from the stage.

I also think room objects should be addable without them existing in stage. For instance if you want an object that has two states (such as the jacket with DNA analyzer in LZ currently), you should be able to add it "back" after destruction. You should have position, size, scale of added room objects definable in the interaction. But not quite sure if this is better than just hiding/showing objects that are defined in the room definition. Current code hides some destroyed things and outright destroys others.

**Comment by evktalo** [comment]
We'll go with this: room objects are defined in each room, added by showing them and removing by hiding them. If you want to move an object, create (copypaste) another object with different position. :P

Inventory items are stored in an invisibile layer when they're not in the inventory (or being dragged).

**Comment by evktalo** [comment]
Done in 9e5cd95 - playing sequences (#35) is not implemented yet.
