### ISSUE TITLE
Default text not used as fallback with item interactions

### ISSUE THREAD

**Issue by Kauko** [evktalo/kiigame#58]
If no text exists for interaction A -> B, the default text should be used as a fallback. This is not done, and instead the code fails because it can't find the requested text from the json. The end result is that the interaction is not finished and the item stays on top of the object (it does not return to the inventory). 

The player can drag the item back and continue playing.

**Comment by evktalo** [comment]
Looks like the code requires that texts.json has an entry called "default", and it has to have a text for "examine". If this doesn't exist, then it happens like in the above description. I think the fix is that the game should complain if the default-examine text doesn't exist.

As a side note, there seem to be two checks where it falls back to the default text, one is when the monologue is actually printed and the other is in the dragend event handler, where it stops the game mechanisms (opening the door or so) from proceeding if the text for the interaction doesn't exist.

**Comment by evktalo** [comment]
re: Side note, the check in monologue function if reached when items/objects are examined, and the latter is when item is used on item/object.

**Comment by evktalo** [comment]
The per-item definable default is a good feature for items, so it should definitely look for that instead of what currently happens.
